// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6FtaA6eclMvYZadB_0RPGuVqPgkI4Uvo',
    appId: '1:925062929638:web:f6c9c265898d3e296c6f27',
    messagingSenderId: '925062929638',
    projectId: 'coffee-e7117',
    authDomain: 'coffee-e7117.firebaseapp.com',
    storageBucket: 'coffee-e7117.appspot.com',
    measurementId: 'G-0BRG2XCQT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpUo2-w7qVhe7QEHAJQlLbL7cfJpS1ZI8',
    appId: '1:925062929638:android:c7444d84b04ea9866c6f27',
    messagingSenderId: '925062929638',
    projectId: 'coffee-e7117',
    storageBucket: 'coffee-e7117.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHVIZBa4DubXyIIqyZfeCGJ75Ut9lkt18',
    appId: '1:925062929638:ios:f860994e609396796c6f27',
    messagingSenderId: '925062929638',
    projectId: 'coffee-e7117',
    storageBucket: 'coffee-e7117.appspot.com',
    androidClientId: '925062929638-9be3godstu9ap1mev4odl3v6rau1g1m9.apps.googleusercontent.com',
    iosClientId: '925062929638-0km4otsu6spssio52r6fqf8jkuqfl68c.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHVIZBa4DubXyIIqyZfeCGJ75Ut9lkt18',
    appId: '1:925062929638:ios:f860994e609396796c6f27',
    messagingSenderId: '925062929638',
    projectId: 'coffee-e7117',
    storageBucket: 'coffee-e7117.appspot.com',
    androidClientId: '925062929638-9be3godstu9ap1mev4odl3v6rau1g1m9.apps.googleusercontent.com',
    iosClientId: '925062929638-0km4otsu6spssio52r6fqf8jkuqfl68c.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6FtaA6eclMvYZadB_0RPGuVqPgkI4Uvo',
    appId: '1:925062929638:web:2f094644d8262e056c6f27',
    messagingSenderId: '925062929638',
    projectId: 'coffee-e7117',
    authDomain: 'coffee-e7117.firebaseapp.com',
    storageBucket: 'coffee-e7117.appspot.com',
    measurementId: 'G-H9RDRQLPMT',
  );

}